# ==============================
# FILE UPLOAD
# ==============================


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

qa.upload.path=D:/uploads/qa_docs/

# ==============================
# DATABASE
# ==============================

spring.datasource.name=jobportal
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=jobportal;trustServerCertificate=true
#spring.datasource.username=remoteuser
#spring.datasource.password=remote@321
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=jobportal;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:remoteuser}
spring.datasource.password=${DB_PASSWORD:remote@321}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update


# ==============================
# EMAIL
# ==============================

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=deepakverma63427258@gmail.com
#spring.mail.password=${MAIL_PASSWORD}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# ==============================
# SERVER
# ==============================

server.address=0.0.0.0
server.port=8091

server.ssl.enabled=true
server.ssl.key-alias=auth-service
server.ssl.key-store=classpath:auth-service.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=remote

spring.main.allow-circular-references=true
server.error.whitelabel.enabled=false